### ISSUE TITLE
BWA?

### ISSUE THREAD

**Issue by davemcg** [aquaskyline/Skyhawk#1]
Is there testing or *guess* whether the BWA aligner is similar enough to use the novoalign aligned model?

**Comment by aquaskyline** [comment]
We have a plan to provide models on BWA and ISAAC alignments. But before that, models trained on novoalign should be good enough.

**Comment by aquaskyline** [comment]
pcr and pcr-free models using isaac alignments were added.

**Comment by aquaskyline** [comment]
Additional experiments show that BWA alignments benefit from using the novoalign aligned models. So in conclusion, we suggest users to use the novoalign aligned models on BWA alignments.

<img width="688" alt="snapshot 2018-05-18 at 1 37 44 pm" src="https://user-images.githubusercontent.com/895289/40217708-cfd2cb34-5aa0-11e8-8864-b49be3309ff8.png">
