### ISSUE TITLE
xrange is not defined

### ISSUE THREAD

**Issue by B1T0** [aquaskyline/Skyhawk#2]
Hey there,

I tried to run Skyhawk using your test data but it failed. This is the command I ran:
```
python ./skyhawk/validateVar.py --chkpnt_fn ./trainedModels/fullv3-illumina-novoalign-hg001+hg002+hg003+hg004+hg005-hg38/learningRate1e-3.epoch100.learningRate1e-4.epoch200 --ref_fn ./testingData/chr21/chr21.fa --bam_fn ./testingData/chr21/chr21.bam --vcf_fn ./testingData/chr21/chr21.vcf --thread 20 --val_fn validationOutput.txt
```
This is the error message I get:
```
Traceback (most recent call last):
  File "./skyhawk/validateVar.py", line 279, in <module>
    Run(args)
  File "./skyhawk/validateVar.py", line 83, in Run
    cpuSet = ",".join(str(x) for x in random.sample(xrange(0, maxCpus), numCpus))
NameError: name 'xrange' is not defined
```

I think I get this error because xrange is not defined in python 3.x.x. Do I have to run it in python 2? I could not find a hint to that in your readme file.

**Comment by aquaskyline** [comment]
Thanks for the report. Skyhawk requires Python 2.7. "Python 2.7 required" added to the README.

**Comment by B1T0** [comment]
All right! I will test it again. Thanks :+1:
