### ISSUE TITLE
Does it work on Multisample VCF as well ?

### ISSUE THREAD

**Issue by snashraf** [aquaskyline/Skyhawk#4]
Hi ,

Thanks for a wonderful tool. 
Any idea if we can use this on multisample VCF as well ? 

Thanks
Najeeb

**Comment by aquaskyline** [comment]
Skyhawk supports only individual sample VCF, but splitting a multisample VCF into individual sample VCF files can be done easily. You can split a multisample VCF into individual VCF files according to the methods available here: https://www.biostars.org/p/78929/

**Comment by snashraf** [comment]
Hi,
yes I know its easy to extract individual VCF from mergd VCF file. I think it would be good when we can access individual file from merged VCF file without extracting it every time as this will save lot of overhead. Any way thanks again .
Najeeb
