### ISSUE TITLE
model for b37 or cross-compatibility with hg19

### ISSUE THREAD

**Issue by AndrewCarroll** [aquaskyline/Skyhawk#6]
In my experience, a plurality of clinical operations use the b37 reference genome. It seems that the hg19 model is not cross compatible when I attempt to execute it (very unfortunate given that the only meaningful difference in this context is the "chr" string on the 24 full chromosomes).

It would be good to either have Skyhawk recognize b37 and cross-apply hg19, or to make a model for b37.

**Comment by aquaskyline** [comment]
The model itself doesn't aware of the chromosome ID, and as long as the reference, VCF and BAM inputs are using the same set of chromosome IDs, the current implementation should work fine. Did you mean that Skyhawk should consider, say, "chr1" in VCF or BAM the same as "1" when b37 is used as reference?

**Comment by aquaskyline** [comment]
Skyhawk now generates error and exits early if the ctgName input mismatch the input reference genome.
