### ISSUE TITLE
Please make sure your VCF input is sorted. Skyhawk exited.

### ISSUE THREAD

**Issue by msnoon** [aquaskyline/Skyhawk#9]
HI, I am getting this vcf not sorted error on my data set  even though its sorted. I get the same error message on provided testingData. Any help would be appreciated.

Please make sure your VCF input is sorted. Skyhawk exited.
['chr21', '14435812', '.', 'AGT', 'AGTGT,A', '50', 'PASS', 'platforms=2;platformnames=Illumina,10X;datasets=2;datasetnames=HiSeqPE300x,10XChromium;callsets=3;callsetnames=HiSeqPE300xGATK,HiSeqPE300xfreebayes,10XGATKhaplo;datasetsmissingcall=CGnormal,IonExome,SolidPE50x50bp,SolidSE75bp;callable=CS_HiSeqPE300xGATK_callable;difficultregion=AllRepeats_lt51bp_gt95identity_merged', 'GT:DP:ADALL:AD:GQ:IGT:IPS:PS', '1|2:300:1,63,82:1,63,82:198:2|1:.:PATMAT']
['chr21', '14435746', '.', 'C', 'T', '222', '.', '.', 'GT:GQ:DP', '0/1:222:28']

here is my command:

python /samtools-1.8/Skyhawk/skyhawk/validateVar.py --chkpnt_fn /samtools-1.8/Skyhawk/trainedModels/illumina-novoalign-2500-tspcrfree-hg001+hg002+hg003+hg004+hg005-hg38/learningRate1e-3.epoch100.learningRate1e-4.epoch200 --ref_fn ./testingData/chr21/chr21.fa --bam_fn ./testingData/chr21/chr21.bam --vcf_fn ./testingData/chr21/chr21.vcf --thread 2 --val_fn validatnOutPut.txt

**Comment by aquaskyline** [comment]
your code base might not be updated, please "git pull" first and try again.

**Comment by aquaskyline** [comment]
the md5 of validateVar.py should be 0b7a1b2e6ae804a8af21c4139aa72603.
